name: atreeon_svg_tools
description: Convert svg files to single line .dart files and standardises the size & top, bottom, left & right
version: 0.0.1+1
  #a.b.c+d
    #d=documentation, package, ci or publishing change only (doesn't affect package user)
    #c=bug fix or a very minor change to package (text or layout)
    #b=new feature
#homepage: https://atreeon.com
#repository: https://github.com/atreeon/XXX
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  svg_line_standardise:
    path: ../../dart/svg_line_standardise
  flutter:
    sdk: flutter
  go_router: ^5.0.5
  dartx: ^0.6.0
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0
  google_fonts: ^3.0.1
  atreeon_menu_flutter: ^0.1.0
  logging: ^1.1.0
  shared_preferences: ^2.0.13
  atreeon_datagrid_responsive: ^0.0.2+2
  adaptive_dialog: ^1.8.0+1
  file_picker: ^5.2.5
  flutter_svg: ^2.0.2
  path_parsing: ^1.0.1
  vector_graphics: ^1.1.0
  vector_graphics_codec: ^1.1.0
  vector_graphics_compiler: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
